version: '3'

services:
  web:
    build:
      context: ./backend
      dockerfile: ./compose/backend/backend.dockerfile
    image: blog_backend_service
    stdin_open: true
    container_name: blog_backend_service
    platform: linux/x86_64
    volumes:
      - ./backend:/app:z
    ports:
      - "8000:8000"
    command: /start
    env_file:
      - .env.local
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: blog_db_service
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env.local
    ports:
      - "8001:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: blog_pgadmin_service
    depends_on:
      - db
    env_file:
      - .env.local
    ports:
      - "9000:5050"
