exclude: "^docs/|/migrations/"
default_stages: [commit]
default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: ["--config=backend/setup.cfg"]
        additional_dependencies: [
          "flake8-isort==5.0.0",
          "flake8-docstrings==1.6.0",
        ]
#
#  - repo: local
#    hooks:
#      - id: mypy
#        name: mypy
#        stages: [push]
#        entry: mypy .
#        args: ["--config-file=setup.cfg"]
#        language: system
#        pass_filenames: false
#        always_run: true

      # sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
